### ISSUE TITLE
jQuery Conversion

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#251]
### I have added a TODO list below

This issue documents areas which need converting to jQuery. This is an attempt to make converting what's left easier, and making it clear how much work needs to be done.
- [x] Admin CP
  - [x] theme.js (split into two: theme_properties.js and theme.js)
  - [x] peeker.js
  - [x] Implement modals where necessary (popupWindow)
    - [x] Mail Error logs
    - [x] Mail Logs
    - [x] Mass Mail
    - [x] IP Lookup
  - [x] Replace CodePress by CodeMirror
  - [x] Fix popupMenu
  - [x] Re-write admin.js (contains delete confirmation)
  - [x] Re-write mycode_sandbox.js (handles the sandbox for MyCode)
  - [x] Re-write quick_perm_editor.js (needs a new Sortable plugin)
  - [x] Re-write tabs.js
  - [x] Re-write users.js (note: doesn't seem to have anything important?)
  - [x] Re-write view_manager.js (requires a new Sortable plugin)
  - [x] SCEditor must be used in the Signature field (Edit User) instead of the old editor (#539)
  - [x] The Show Additional Options link when adding a forum needs to be fixed
  - [x] Settings search box needs to be fixed
  - [x] Replace hardcoded text in JS by language variables
    - [x] admin/jscripts/search.js
    - [x] admin/jscripts/mycode_sandbox.js
    - [x] admin/jscripts/themes.js
- [x] Forum front-end
  - [x] Implement Select2 #375 (replace Autocomplete.js)
  - [x] Implement modals where necessary (popupWindow parameter fixes; PHP code changes; Template changes)
    - [x] Buddy List popup
    - [x] Add reputation
    - [x] Report reputation
    - [x] Report post (re-write thread.js)
    - [x] Report user
    - [x] Get IP info (ModCP -> IP Search)
    - [x] MSN/AIM/YAHOO
    - [x] Who Posted
  - [x] Inline Edit (Forum Display -> Edit subject on hold) (inline_edit.js)
  - [x] Quick Reply (re-write thread.js ; uses jEditable)
  - [x] Quick Edit (re-write thread.js)
  - [x] Multi Quote (re-write post.js and re-write thread.js)
  - [x] Insert Into Post (attachment)
  - [x] Remove attachment (re-write post.js)
  - [x] Replace existing editor by SCEditor
  - [x] Inline Moderation (re-write inline_moderation.js)
  - [x] Registration form validation (re-write validator.js)
  - [x] Confirm dialogues replaced by Impromptu
  - [x] Convert popupMenu (Note: can be found in jquery.plugins.js now)
  - [x] Replace alerts by jGrowl notifications (jGrowl can be found jquery.plugins.js)
    Below you can find detailed information about what's left.
  - [x] Add Modals plugin (jquery modal can be found in jquery.plugins.js)
  - [x] Add Impromptu plugin (Impromptu can be found in jquery.plugins.js)
  - [x] Add bbcodes_sceditor.js (comes from the SCEditor plugin for MyBB - no point in re-inventing the wheel)
  - [x] Captcha (re-write captcha.js)
  - [x] Mark as Read (re-write general.js)
  - [x] popupWindow (re-write general.js)
  - [x] Delete calendar event (re-write general.js)
  - [x] Delete reputation (re-write general.js)
  - [x] Submit reputation (re-write general.js)
  - [x] Change Language (re-write general.js)
  - [x] Detect DST change (re-write general.js)
  - [x] Dismiss PM notice (re-write general.js)
  - [x] Delete announcement (re-write general.js)
  - [x] Expandable/Collapsible (re-write general.js)
  - [x] Implement jQuery Cookie plugin (appended to general.js)
  - [x] Fix ratings (re-write rating.js)
  - [x] Quick delete post (re-write thread.js)
  - [x] Show ignored post (re-write thread.js)
  - [x] UserCP Edit Lists (Buddy/Ignore) (re-write usercp.js)
  - [x] UserCP Select from buddies in compose message #629
  - [x] Select All boxes
  - [x] ModCP Mass Controls
  - [x] Calendar (onfocus events must be converted)
  - [x] Replace hardcoded text in JS by language variables
    - [x] usercp.js
    - [x] thread.js
    - [x] rating.js
    - [x] post.js
    - [x] inline_moderation.js
    - [x] inline_edit.js
    - [x] general.js
    - [x] captcha.js
    - [x] report.js
  - [x] Convert smilies box
  - [x] Warnings - Send PM Notification (if SCEditor is invisible by default, the height of the iframe and LTR textarea is not properly calculated and therefore when we ticked the Send PM checkbox to show the editor box, it had 0px height; this was fixed by hiding the editor after the document has been loaded) - related to https://github.com/samclarke/SCEditor/issues/276

Feel free to point out any I've missed.
