### ISSUE TITLE
Remove code obsolete on PHP >= 8.2

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4549]
- [x] #4550
- [x] `magic_quotes` function calls #4882
- [x] implementation and/or usage of randomness functions (e.g. `secure_binary_seed_rng()`, `secure_seed_rng()`, `my_rand()`) #4886
- [x] [`Services_JSON` polyfill](https://github.com/mybb/mybb/blob/dev-1.9/inc/3rdparty/json/json.php) #4880
- [x]  `my_hash_equals()` & usage #4885
- [x] #4916
- [x] #4917
- [x] other fallback code with explicit PHP version checks (e.g. using `PHP_VERSION`) #4882
- [x] other fallback code with implicit PHP version checks (e.g. using `function_exists()`, `extension_loaded()`)
  - [x] `array_column` #4908
  - [x] `sha1` #4909
 - [x] PHP configuration checks
   - [x]  [`safe_mode`](https://php-legacy-docs.zend.com/manual/php5/en/features.safe-mode) #4905
   - [x] [`register_globals`](https://php-legacy-docs.zend.com/manual/php5/en/ini.core#ini.register-globals) #4904
 - [x] PHP deprecated functions
   - [x] Replace `utf8_decode` and `utf8_encode` #4807

**Comment by Sama34** [comment]
Correct me if I'm wrong, but `utf8_encode` is still used in the codebase.

**Comment by arcalys** [comment]
The remaining calls to `utf8_encode` are:
- a custom implementation in class `MailHandler`
- a call in a vendor library (diff)

I think this can be closed @Sama34.
