### ISSUE TITLE
Minor PHP errors

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#4711]
Under PHP 8.2 I found the following errors :

- [x]  `Deprecated: str_replace(): Passing null to parameter '#3 ($subject) of type array|string is deprecated in /var/www/inc/class_error.php on line 182`
- [x]  `Deprecated: Automatic conversion of false to array is deprecated in /var/www/inc/class_templates.php on line 100`
- [x]  `Deprecated: explode(): Passing null to parameter # 2 ($string) of type string is deprecated in /var/www/inc/functions.php on line 1697`
- [x]  `Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/inc/functions.php on line 6104`
- [ ]  ~~`Warning [2] Undefined array key "fragment" - Line: 1494 - File: inc/class_parser.php PHP 8.2.6 (Linux)`~~
- [x]  `Warning [2] Undefined array key 0 - Line: 1587 - File: inc/class_parser.php PHP 8.2.6 (Linux)`
- [x]  `Deprecated: Creation of dynamic property PhpMail::$sendmail is deprecated in /var/www/inc/mailhandlers/php.php on line 39`
- [x]  `Deprecated: Creation of dynamic property PhpMail::$sendmail_from is deprecated in /var/www/inc/mailhandlers/php.php on line 48`
- [x]  `Warning [2] Undefined array key "posthash" - Line: 1804 - File: inc/datahandlers/post.php PHP 8.2.6 (Linux)`
- [x]  `Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/inc/functions.php on line 5717`
- [x]  `Deprecated: Automatic conversion of false to array is deprecated in /var/www/misc.php on line 728`
- [x]  `Warning [2] Undefined array key "processed" - Line: 2986 - File: admin/modules/user/users.php PHP 8.2.6 (Linux)`
- [x]  `Warning [2] Undefined array key "additionalgroups" - Line: 3086 - File: admin/modules/user/users.php PHP 8.2.6 (Linux)`
- [x]  `Warning [2] Undefined array key "additionalgroups" - Line: 3088 - File: admin/modules/user/users.php PHP 8.2.6 (Linux)`
- [x]  `Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/admin/modules/user/users.php on line 3088`
- [x]  `Warning [2] Undefined array key "usergroup" - Line: 3091 - File: admin/modules/user/users.php PHP 8.2.6 (Linux)`
- [x]  `Warning [2] Undefined array key "displaygroup" - Line: 3093 - File: admin/modules/user/users.php PHP 8.2.6 (Linux)`
- [x] `Warning [2] Undefined variable $written - Line: 674 - File: install/upgrade.php PHP 8.2.6 (Linux)`

It is possible some of these are already fixed so I will come back to the issue when I finish updating some projects.

**Comment by RevertIT** [comment]
A quick fix would be 
1# 
```php
if(empty($gettemplate))
{
	$gettemplate = array();
	$gettemplate['template'] = "";
}
```

2# `$groups = explode(",", (string) $gid);`
3# `if(strtolower((string) $lang->settings['charset']) == "utf-8")`

**Comment by Eldenroot** [comment]
> A quick fix would be 1#
> 
> ```
> if(empty($gettemplate))
> {
> 	$gettemplate = array();
> 	$gettemplate['template'] = "";
> }
> ```
> 
> 2# `$groups = explode(",", (string) $gid);` 3# `if(strtolower((string) $lang->settings['charset']) == "utf-8")`

can you create a PR?
