### ISSUE TITLE
Move hard-coded words to language files

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#616]
- [x] modcp_modqueue_attachments_attachment Template -> Post: (fixed in #768 )
- [x] report_reasons Template -> If 'Other' please provide a reason for reporting this content. (fixed in #768 )
- [x] admin/forum/attachments.php: line 417 & 576 -> Scanning... (fixed in #768 )
- [x] managegroup_adduser template -> Search for a user (fixed in #768 )
- [x] member_register_referrer template -> Search for a user (fixed in #768 )
- [x] memberlist template -> Search for a user (fixed in #768 )
- [x] memberlist_search -> Search for a user (fixed in #768 )
- [x] modcp_banuser -> Search for a user (fixed in #768 )
- [x] modcp_warninglogs -> Search for a user (fixed in #768 )
- [x] private_send_autocomplete -> to select2 -> Search for a user (fixed in #768 )
- [x] private_send_autocomplete -> bcc select2 -> Search for a user (fixed in #768 )
- [x] search -> Search for a user (fixed in #768 )
- [x] usercp_editlists -> Search for a movie -> :o ( must change to user! ) (fixed in #768 )
- [x] usercp_editlists -> Search for a user (fixed in #768 )
- [x] install/upgrade.php lines 255/259
