### ISSUE TITLE
Move hard-coded words to language files

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#617]
- [x] modcp_modqueue_attachments_attachment template -> Post: (fixed in #767 )
- [x] admin/modules/forum/attachments.php:line 417 & 576 -> Scanning.. (fixed in #767 )
- [x] install/upgrade.php:line 223/260 (fixed in #767 )
