### ISSUE TITLE
Use get_inactive_forums() where necessary.

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#679]
The following places should use the get_inactive_forums() function to "hide" inactive forums results.
- [x] ./misc.php Line#584
- [x] ./modcp.php Line#74
- [x] ./newreply.php Line#717
- [x] ./newthread.php Line#460
- [x] ./portal.php Line#56 #532
- [x] ./stats.php Line#52
- [x] ./usercp.php Line#3355
- [x] ./xmlhttp.php Line#532
- [x] ./inc/functions_online.php Line#470

Feel free to update.
